# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'iprmpasef_exporter_template.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import QCoreApplication, QMetaObject, QRect
from PySide6.QtWidgets import QCheckBox, QComboBox, QLabel, QLineEdit, QPushButton, QRadioButton, QSpinBox, QWidget


class Ui_IprmpasefExporterWindow(object):
    def setupUi(self, IprmpasefExporterWindow):
        if not IprmpasefExporterWindow.objectName():
            IprmpasefExporterWindow.setObjectName(u"IprmpasefExporterWindow")
        IprmpasefExporterWindow.resize(522, 333)
        self.centralwidget = QWidget(IprmpasefExporterWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.ScilsLabel = QLabel(self.centralwidget)
        self.ScilsLabel.setObjectName(u"ScilsLabel")
        self.ScilsLabel.setGeometry(QRect(10, 10, 261, 16))
        self.ScilsLineEdit = QLineEdit(self.centralwidget)
        self.ScilsLineEdit.setObjectName(u"ScilsLineEdit")
        self.ScilsLineEdit.setGeometry(QRect(10, 30, 181, 22))
        self.ScilsBrowseButton = QPushButton(self.centralwidget)
        self.ScilsBrowseButton.setObjectName(u"ScilsBrowseButton")
        self.ScilsBrowseButton.setGeometry(QRect(200, 30, 75, 24))
        self.FeatureListIdLabel = QLabel(self.centralwidget)
        self.FeatureListIdLabel.setObjectName(u"FeatureListIdLabel")
        self.FeatureListIdLabel.setGeometry(QRect(10, 60, 261, 16))
        self.FeatureListIdCombo = QComboBox(self.centralwidget)
        self.FeatureListIdCombo.setObjectName(u"FeatureListIdCombo")
        self.FeatureListIdCombo.setGeometry(QRect(10, 80, 261, 24))
        self.IntensityColumnNameLabel = QLabel(self.centralwidget)
        self.IntensityColumnNameLabel.setObjectName(u"IntensityColumnNameLabel")
        self.IntensityColumnNameLabel.setGeometry(QRect(10, 110, 261, 16))
        self.IntensityColumnNameCombo = QComboBox(self.centralwidget)
        self.IntensityColumnNameCombo.setObjectName(u"IntensityColumnNameCombo")
        self.IntensityColumnNameCombo.setGeometry(QRect(10, 130, 261, 24))
        self.ExportSingleFileCheckbox = QCheckBox(self.centralwidget)
        self.ExportSingleFileCheckbox.setObjectName(u"ExportSingleFileCheckbox")
        self.ExportSingleFileCheckbox.setGeometry(QRect(10, 160, 261, 20))
        self.GetPrecursorFromIsolationWindowCheckbox = QCheckBox(self.centralwidget)
        self.GetPrecursorFromIsolationWindowCheckbox.setObjectName(u"GetPrecursorFromIsolationWindowCheckbox")
        self.GetPrecursorFromIsolationWindowCheckbox.setGeometry(QRect(10, 190, 261, 20))
        self.RelativeIntensityThresholdLabel = QLabel(self.centralwidget)
        self.RelativeIntensityThresholdLabel.setObjectName(u"RelativeIntensityThresholdLabel")
        self.RelativeIntensityThresholdLabel.setGeometry(QRect(10, 220, 171, 16))
        self.RelativeIntensityThresholdSpinBox = QSpinBox(self.centralwidget)
        self.RelativeIntensityThresholdSpinBox.setObjectName(u"RelativeIntensityThresholdSpinBox")
        self.RelativeIntensityThresholdSpinBox.setGeometry(QRect(190, 220, 88, 24))
        self.ExportFormatLabel = QLabel(self.centralwidget)
        self.ExportFormatLabel.setObjectName(u"ExportFormatLabel")
        self.ExportFormatLabel.setGeometry(QRect(300, 10, 211, 16))
        self.ExportFormatCombo = QComboBox(self.centralwidget)
        self.ExportFormatCombo.setObjectName(u"ExportFormatCombo")
        self.ExportFormatCombo.setGeometry(QRect(300, 30, 211, 24))
        self.OutputDirectoryLabel = QLabel(self.centralwidget)
        self.OutputDirectoryLabel.setObjectName(u"OutputDirectoryLabel")
        self.OutputDirectoryLabel.setGeometry(QRect(10, 250, 261, 16))
        self.OutputDirectoryLineEdit = QLineEdit(self.centralwidget)
        self.OutputDirectoryLineEdit.setObjectName(u"OutputDirectoryLineEdit")
        self.OutputDirectoryLineEdit.setGeometry(QRect(10, 270, 171, 22))
        self.OutputDirectoryBrowseButton = QPushButton(self.centralwidget)
        self.OutputDirectoryBrowseButton.setObjectName(u"OutputDirectoryBrowseButton")
        self.OutputDirectoryBrowseButton.setGeometry(QRect(190, 270, 75, 24))
        self.MzmlExportParametersLabel = QLabel(self.centralwidget)
        self.MzmlExportParametersLabel.setObjectName(u"MzmlExportParametersLabel")
        self.MzmlExportParametersLabel.setGeometry(QRect(300, 60, 211, 16))
        self.PolarityLabel = QLabel(self.centralwidget)
        self.PolarityLabel.setObjectName(u"PolarityLabel")
        self.PolarityLabel.setGeometry(QRect(300, 80, 211, 16))
        self.BarebonesMetadataCheckbox = QCheckBox(self.centralwidget)
        self.BarebonesMetadataCheckbox.setObjectName(u"BarebonesMetadataCheckbox")
        self.BarebonesMetadataCheckbox.setGeometry(QRect(300, 130, 211, 20))
        self.MzEncodingLabel = QLabel(self.centralwidget)
        self.MzEncodingLabel.setObjectName(u"MzEncodingLabel")
        self.MzEncodingLabel.setGeometry(QRect(300, 160, 81, 16))
        self.MzEncoding32bitRadio = QRadioButton(self.centralwidget)
        self.MzEncoding32bitRadio.setObjectName(u"MzEncoding32bitRadio")
        self.MzEncoding32bitRadio.setGeometry(QRect(300, 180, 61, 20))
        self.MzEncoding64bitRadio = QRadioButton(self.centralwidget)
        self.MzEncoding64bitRadio.setObjectName(u"MzEncoding64bitRadio")
        self.MzEncoding64bitRadio.setGeometry(QRect(300, 200, 61, 20))
        self.IntensityEncodingLabel = QLabel(self.centralwidget)
        self.IntensityEncodingLabel.setObjectName(u"IntensityEncodingLabel")
        self.IntensityEncodingLabel.setGeometry(QRect(400, 160, 101, 16))
        self.IntensityEncoding32bitRadio = QRadioButton(self.centralwidget)
        self.IntensityEncoding32bitRadio.setObjectName(u"IntensityEncoding32bitRadio")
        self.IntensityEncoding32bitRadio.setGeometry(QRect(400, 180, 61, 20))
        self.IntensityEncoding64bitRadio = QRadioButton(self.centralwidget)
        self.IntensityEncoding64bitRadio.setObjectName(u"IntensityEncoding64bitRadio")
        self.IntensityEncoding64bitRadio.setGeometry(QRect(400, 200, 61, 20))
        self.CompressionLabel = QLabel(self.centralwidget)
        self.CompressionLabel.setObjectName(u"CompressionLabel")
        self.CompressionLabel.setGeometry(QRect(300, 230, 211, 16))
        self.RunButton = QPushButton(self.centralwidget)
        self.RunButton.setObjectName(u"RunButton")
        self.RunButton.setGeometry(QRect(10, 300, 501, 24))
        self.PolarityPositiveRadio = QRadioButton(self.centralwidget)
        self.PolarityPositiveRadio.setObjectName(u"PolarityPositiveRadio")
        self.PolarityPositiveRadio.setGeometry(QRect(300, 100, 71, 20))
        self.PolarityNegativeRadio = QRadioButton(self.centralwidget)
        self.PolarityNegativeRadio.setObjectName(u"PolarityNegativeRadio")
        self.PolarityNegativeRadio.setGeometry(QRect(400, 100, 81, 20))
        self.CompressionZlibRadio = QRadioButton(self.centralwidget)
        self.CompressionZlibRadio.setObjectName(u"CompressionZlibRadio")
        self.CompressionZlibRadio.setGeometry(QRect(300, 250, 51, 20))
        self.CompressionNoneRadio = QRadioButton(self.centralwidget)
        self.CompressionNoneRadio.setObjectName(u"CompressionNoneRadio")
        self.CompressionNoneRadio.setGeometry(QRect(400, 250, 61, 20))
        IprmpasefExporterWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(IprmpasefExporterWindow)

        QMetaObject.connectSlotsByName(IprmpasefExporterWindow)
    # setupUi

    def retranslateUi(self, IprmpasefExporterWindow):
        IprmpasefExporterWindow.setWindowTitle(QCoreApplication.translate("IprmpasefExporterWindow", u"iprm-PASEF Exporter", None))
        self.ScilsLabel.setText(QCoreApplication.translate("IprmpasefExporterWindow", u"SCiLS Lab File (*.slx)", None))
        self.ScilsBrowseButton.setText(QCoreApplication.translate("IprmpasefExporterWindow", u"Browse", None))
        self.FeatureListIdLabel.setText(QCoreApplication.translate("IprmpasefExporterWindow", u"Feature List ID", None))
        self.IntensityColumnNameLabel.setText(QCoreApplication.translate("IprmpasefExporterWindow", u"Intensity Column Name", None))
        self.ExportSingleFileCheckbox.setText(QCoreApplication.translate("IprmpasefExporterWindow", u"Export MS/MS Spectra to Single File", None))
        self.GetPrecursorFromIsolationWindowCheckbox.setText(QCoreApplication.translate("IprmpasefExporterWindow", u"Get Precursor Values from Isolation Window", None))
        self.RelativeIntensityThresholdLabel.setText(QCoreApplication.translate("IprmpasefExporterWindow", u"Relative Intensity Threshold (%)", None))
        self.ExportFormatLabel.setText(QCoreApplication.translate("IprmpasefExporterWindow", u"Export Format", None))
        self.OutputDirectoryLabel.setText(QCoreApplication.translate("IprmpasefExporterWindow", u"Output Directory", None))
        self.OutputDirectoryBrowseButton.setText(QCoreApplication.translate("IprmpasefExporterWindow", u"Browse", None))
        self.MzmlExportParametersLabel.setText(QCoreApplication.translate("IprmpasefExporterWindow", u"mzML Export Parameters", None))
        self.PolarityLabel.setText(QCoreApplication.translate("IprmpasefExporterWindow", u"Polarity", None))
        self.BarebonesMetadataCheckbox.setText(QCoreApplication.translate("IprmpasefExporterWindow", u"Only Include Barebones Metadata", None))
        self.MzEncodingLabel.setText(QCoreApplication.translate("IprmpasefExporterWindow", u"m/z Encoding", None))
        self.MzEncoding32bitRadio.setText(QCoreApplication.translate("IprmpasefExporterWindow", u"32-bit", None))
        self.MzEncoding64bitRadio.setText(QCoreApplication.translate("IprmpasefExporterWindow", u"64-bit", None))
        self.IntensityEncodingLabel.setText(QCoreApplication.translate("IprmpasefExporterWindow", u"Intensity Encoding", None))
        self.IntensityEncoding32bitRadio.setText(QCoreApplication.translate("IprmpasefExporterWindow", u"32-bit", None))
        self.IntensityEncoding64bitRadio.setText(QCoreApplication.translate("IprmpasefExporterWindow", u"64-bit", None))
        self.CompressionLabel.setText(QCoreApplication.translate("IprmpasefExporterWindow", u"Compression", None))
        self.RunButton.setText(QCoreApplication.translate("IprmpasefExporterWindow", u"Run", None))
        self.PolarityPositiveRadio.setText(QCoreApplication.translate("IprmpasefExporterWindow", u"Positive", None))
        self.PolarityNegativeRadio.setText(QCoreApplication.translate("IprmpasefExporterWindow", u"Negative", None))
        self.CompressionZlibRadio.setText(QCoreApplication.translate("IprmpasefExporterWindow", u"zlib", None))
        self.CompressionNoneRadio.setText(QCoreApplication.translate("IprmpasefExporterWindow", u"none", None))
    # retranslateUi

